In [1]:
import glob
import os
import librosa
import librosa.display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import specgram
import tensorflow as tf
import MRCG as mrcg
import scipy.io.wavfile
import wave
import time

%matplotlib inline
plt.style.use('ggplot')


plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = 'Ubuntu'
plt.rcParams['font.monospace'] = 'Ubuntu Mono'
plt.rcParams['font.size'] = 12
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 11
plt.rcParams['figure.titlesize'] = 13

In [2]:
sample_vad_seg_repo = os.path.join('.', 'Data', 'binary_segment')
samples_vad_seg = glob.glob(os.path.join(sample_vad_seg_repo, '*[npy|npz]'), recursive=True)

samples_vad_seg = sorted(samples_vad_seg)   
print(len(samples_vad_seg))

50


In [3]:
sample_vad_seg_repo_20 = os.path.join('.', 'Data', 'binary_segment', '20도')
samples_vad_seg_20 = glob.glob(os.path.join(sample_vad_seg_repo_20, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_20 = sorted(samples_vad_seg_20)   
print(len(samples_vad_seg_20))

36


In [4]:
sample_vad_seg_repo_40 = os.path.join('.', 'Data', 'binary_segment', '40도')
samples_vad_seg_40 = glob.glob(os.path.join(sample_vad_seg_repo_40, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_40 = sorted(samples_vad_seg_40)   
print(len(samples_vad_seg_40))

39


In [5]:
sample_vad_seg_repo_80 = os.path.join('.', 'Data', 'binary_segment', '80도')
samples_vad_seg_80 = glob.glob(os.path.join(sample_vad_seg_repo_80, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_80 = sorted(samples_vad_seg_80)   
print(len(samples_vad_seg_80))

47


In [6]:
sample_vad_seg_repo_100 = os.path.join('.', 'Data', 'binary_segment', '100도')
samples_vad_seg_100 = glob.glob(os.path.join(sample_vad_seg_repo_100, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_100 = sorted(samples_vad_seg_100)   
print(len(samples_vad_seg_100))

51


In [7]:
sample_vad_seg_repo_140 = os.path.join('.', 'Data', 'binary_segment', '140도')
samples_vad_seg_140 = glob.glob(os.path.join(sample_vad_seg_repo_140, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_140 = sorted(samples_vad_seg_140)   
print(len(samples_vad_seg_140))

41


In [8]:
sample_vad_seg_repo_160 = os.path.join('.', 'Data', 'binary_segment', '160도')
samples_vad_seg_160 = glob.glob(os.path.join(sample_vad_seg_repo_160, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_160 = sorted(samples_vad_seg_160)   
print(len(samples_vad_seg_160))

51


In [9]:
list(enumerate(samples_vad_seg))

[(0, './Data/binary_segment/01.npy'),
 (1, './Data/binary_segment/02.npy'),
 (2, './Data/binary_segment/03.npy'),
 (3, './Data/binary_segment/04.npy'),
 (4, './Data/binary_segment/05.npy'),
 (5, './Data/binary_segment/06.npy'),
 (6, './Data/binary_segment/07.npy'),
 (7, './Data/binary_segment/08.npy'),
 (8, './Data/binary_segment/09.npy'),
 (9, './Data/binary_segment/10.npy'),
 (10, './Data/binary_segment/11.npy'),
 (11, './Data/binary_segment/12.npy'),
 (12, './Data/binary_segment/13.npy'),
 (13, './Data/binary_segment/14.npy'),
 (14, './Data/binary_segment/15.npy'),
 (15, './Data/binary_segment/16.npy'),
 (16, './Data/binary_segment/17.npy'),
 (17, './Data/binary_segment/18.npy'),
 (18, './Data/binary_segment/19.npy'),
 (19, './Data/binary_segment/20.npy'),
 (20, './Data/binary_segment/21.npy'),
 (21, './Data/binary_segment/22.npy'),
 (22, './Data/binary_segment/23.npy'),
 (23, './Data/binary_segment/24.npy'),
 (24, './Data/binary_segment/25.npy'),
 (25, './Data/binary_segment/26.npy

In [10]:
list(enumerate(samples_vad_seg_20))

[(0, './Data/binary_segment/20도/output00.npz'),
 (1, './Data/binary_segment/20도/output01.npz'),
 (2, './Data/binary_segment/20도/output02.npz'),
 (3, './Data/binary_segment/20도/output03.npz'),
 (4, './Data/binary_segment/20도/output04.npz'),
 (5, './Data/binary_segment/20도/output05.npz'),
 (6, './Data/binary_segment/20도/output06.npz'),
 (7, './Data/binary_segment/20도/output07.npz'),
 (8, './Data/binary_segment/20도/output08.npz'),
 (9, './Data/binary_segment/20도/output09.npz'),
 (10, './Data/binary_segment/20도/output10.npz'),
 (11, './Data/binary_segment/20도/output11.npz'),
 (12, './Data/binary_segment/20도/output12.npz'),
 (13, './Data/binary_segment/20도/output13.npz'),
 (14, './Data/binary_segment/20도/output14.npz'),
 (15, './Data/binary_segment/20도/output15.npz'),
 (16, './Data/binary_segment/20도/output16.npz'),
 (17, './Data/binary_segment/20도/output17.npz'),
 (18, './Data/binary_segment/20도/output18.npz'),
 (19, './Data/binary_segment/20도/output19.npz'),
 (20, './Data/binary_segment/2

In [11]:
list(enumerate(samples_vad_seg_40))

[(0, './Data/binary_segment/40도/output00.npz'),
 (1, './Data/binary_segment/40도/output01.npz'),
 (2, './Data/binary_segment/40도/output02.npz'),
 (3, './Data/binary_segment/40도/output03.npz'),
 (4, './Data/binary_segment/40도/output04.npz'),
 (5, './Data/binary_segment/40도/output05.npz'),
 (6, './Data/binary_segment/40도/output06.npz'),
 (7, './Data/binary_segment/40도/output07.npz'),
 (8, './Data/binary_segment/40도/output08.npz'),
 (9, './Data/binary_segment/40도/output09.npz'),
 (10, './Data/binary_segment/40도/output10.npz'),
 (11, './Data/binary_segment/40도/output11.npz'),
 (12, './Data/binary_segment/40도/output12.npz'),
 (13, './Data/binary_segment/40도/output13.npz'),
 (14, './Data/binary_segment/40도/output14.npz'),
 (15, './Data/binary_segment/40도/output15.npz'),
 (16, './Data/binary_segment/40도/output16.npz'),
 (17, './Data/binary_segment/40도/output17.npz'),
 (18, './Data/binary_segment/40도/output18.npz'),
 (19, './Data/binary_segment/40도/output19.npz'),
 (20, './Data/binary_segment/4

In [12]:
list(enumerate(samples_vad_seg_80))

[(0, './Data/binary_segment/80도/output00.npz'),
 (1, './Data/binary_segment/80도/output01.npz'),
 (2, './Data/binary_segment/80도/output02.npz'),
 (3, './Data/binary_segment/80도/output03.npz'),
 (4, './Data/binary_segment/80도/output04.npz'),
 (5, './Data/binary_segment/80도/output05.npz'),
 (6, './Data/binary_segment/80도/output06.npz'),
 (7, './Data/binary_segment/80도/output07.npz'),
 (8, './Data/binary_segment/80도/output08.npz'),
 (9, './Data/binary_segment/80도/output09.npz'),
 (10, './Data/binary_segment/80도/output10.npz'),
 (11, './Data/binary_segment/80도/output11.npz'),
 (12, './Data/binary_segment/80도/output12.npz'),
 (13, './Data/binary_segment/80도/output13.npz'),
 (14, './Data/binary_segment/80도/output14.npz'),
 (15, './Data/binary_segment/80도/output15.npz'),
 (16, './Data/binary_segment/80도/output16.npz'),
 (17, './Data/binary_segment/80도/output17.npz'),
 (18, './Data/binary_segment/80도/output18.npz'),
 (19, './Data/binary_segment/80도/output19.npz'),
 (20, './Data/binary_segment/8

In [13]:
list(enumerate(samples_vad_seg_100))

[(0, './Data/binary_segment/100도/output00.npz'),
 (1, './Data/binary_segment/100도/output01.npz'),
 (2, './Data/binary_segment/100도/output02.npz'),
 (3, './Data/binary_segment/100도/output03.npz'),
 (4, './Data/binary_segment/100도/output04.npz'),
 (5, './Data/binary_segment/100도/output05.npz'),
 (6, './Data/binary_segment/100도/output06.npz'),
 (7, './Data/binary_segment/100도/output07.npz'),
 (8, './Data/binary_segment/100도/output08.npz'),
 (9, './Data/binary_segment/100도/output09.npz'),
 (10, './Data/binary_segment/100도/output10.npz'),
 (11, './Data/binary_segment/100도/output11.npz'),
 (12, './Data/binary_segment/100도/output12.npz'),
 (13, './Data/binary_segment/100도/output13.npz'),
 (14, './Data/binary_segment/100도/output14.npz'),
 (15, './Data/binary_segment/100도/output15.npz'),
 (16, './Data/binary_segment/100도/output16.npz'),
 (17, './Data/binary_segment/100도/output17.npz'),
 (18, './Data/binary_segment/100도/output18.npz'),
 (19, './Data/binary_segment/100도/output19.npz'),
 (20, './D

In [14]:
list(enumerate(samples_vad_seg_140))

[(0, './Data/binary_segment/140도/output00.npz'),
 (1, './Data/binary_segment/140도/output01.npz'),
 (2, './Data/binary_segment/140도/output02.npz'),
 (3, './Data/binary_segment/140도/output03.npz'),
 (4, './Data/binary_segment/140도/output04.npz'),
 (5, './Data/binary_segment/140도/output05.npz'),
 (6, './Data/binary_segment/140도/output06.npz'),
 (7, './Data/binary_segment/140도/output07.npz'),
 (8, './Data/binary_segment/140도/output08.npz'),
 (9, './Data/binary_segment/140도/output09.npz'),
 (10, './Data/binary_segment/140도/output10.npz'),
 (11, './Data/binary_segment/140도/output11.npz'),
 (12, './Data/binary_segment/140도/output12.npz'),
 (13, './Data/binary_segment/140도/output13.npz'),
 (14, './Data/binary_segment/140도/output14.npz'),
 (15, './Data/binary_segment/140도/output15.npz'),
 (16, './Data/binary_segment/140도/output16.npz'),
 (17, './Data/binary_segment/140도/output17.npz'),
 (18, './Data/binary_segment/140도/output18.npz'),
 (19, './Data/binary_segment/140도/output19.npz'),
 (20, './D

In [15]:
list(enumerate(samples_vad_seg_160))

[(0, './Data/binary_segment/160도/output00.npz'),
 (1, './Data/binary_segment/160도/output01.npz'),
 (2, './Data/binary_segment/160도/output02.npz'),
 (3, './Data/binary_segment/160도/output03.npz'),
 (4, './Data/binary_segment/160도/output04.npz'),
 (5, './Data/binary_segment/160도/output05.npz'),
 (6, './Data/binary_segment/160도/output06.npz'),
 (7, './Data/binary_segment/160도/output07.npz'),
 (8, './Data/binary_segment/160도/output08.npz'),
 (9, './Data/binary_segment/160도/output09.npz'),
 (10, './Data/binary_segment/160도/output10.npz'),
 (11, './Data/binary_segment/160도/output11.npz'),
 (12, './Data/binary_segment/160도/output12.npz'),
 (13, './Data/binary_segment/160도/output13.npz'),
 (14, './Data/binary_segment/160도/output14.npz'),
 (15, './Data/binary_segment/160도/output15.npz'),
 (16, './Data/binary_segment/160도/output16.npz'),
 (17, './Data/binary_segment/160도/output17.npz'),
 (18, './Data/binary_segment/160도/output18.npz'),
 (19, './Data/binary_segment/160도/output19.npz'),
 (20, './D

In [16]:
sample_data_repo = os.path.join('.', 'Data', 'sample_data', 't3_audio')
samples = glob.glob(os.path.join(sample_data_repo, '**', '*wav'), recursive=True)
samples = sorted(samples)   # sort the samples
print(len(samples))

50


In [17]:
sample_data_20 = os.path.join('.', 'Data', 'sample_data', '20도')
samples_20 = glob.glob(os.path.join(sample_data_20, '**', '*wav'), recursive=True)
samples_20 = sorted(samples_20)   # sort the samples
print(len(samples_20))

36


In [18]:
sample_data_40 = os.path.join('.', 'Data', 'sample_data', '40도')
samples_40 = glob.glob(os.path.join(sample_data_40, '**', '*wav'), recursive=True)
samples_40 = sorted(samples_40)   # sort the samples
print(len(samples_40))

39


In [19]:
sample_data_80 = os.path.join('.', 'Data', 'sample_data', '80도')
samples_80 = glob.glob(os.path.join(sample_data_80, '**', '*wav'), recursive=True)
samples_80 = sorted(samples_80)   # sort the samples
print(len(samples_80))

47


In [20]:
sample_data_100 = os.path.join('.', 'Data', 'sample_data', '100도')
samples_100 = glob.glob(os.path.join(sample_data_100, '**', '*wav'), recursive=True)
samples_100 = sorted(samples_100)   # sort the samples
print(len(samples_100))

51


In [21]:
sample_data_140 = os.path.join('.', 'Data', 'sample_data', '140도')
samples_140 = glob.glob(os.path.join(sample_data_140, '**', '*wav'), recursive=True)
samples_140 = sorted(samples_140)   # sort the samples
print(len(samples_140))

41


In [22]:
sample_data_160 = os.path.join('.', 'Data', 'sample_data', '160도')
samples_160 = glob.glob(os.path.join(sample_data_160, '**', '*wav'), recursive=True)
samples_160 = sorted(samples_160)   # sort the samples
print(len(samples_160))

51


In [23]:
def mrcg_transpose(file_path, sr=48000):
    X, sample_rate = librosa.load(file_path, sr=sr, mono=False)
    mrcg_L = mrcg.mrcg_extract(X[0], sample_rate)
    mrcg_R = mrcg.mrcg_extract(X[1], sample_rate)
    
    return mrcg_L, mrcg_R

In [24]:
def generate_instances(array_2d, seq_len, hop, label):

    row_size, col_size = array_2d.shape[0], array_2d.shape[1]
    rate = len(label)/col_size
    stack_array = []    # 4D tensor that will hold the instances
    label_array = []

    j=0
    while j <= (col_size - (seq_len+1)): 
        context_frame = array_2d[:, j:(j+seq_len)]
        seg_label = round(label[int(j*rate):int((j+seq_len)*rate)].mean())
        
        stack_array.append(context_frame[:,:,np.newaxis])      # make context_frame to 3d tensor and append 
        label_array.append(seg_label)
            
        j = j+hop
        
    return np.stack(stack_array, axis=0), label_array

In [25]:
mrcg_L_tensor = []
mrcg_R_tensor = []
label_list = []

for i in range(0,50):
    deg = np.load(samples_vad_seg[i])
    if('npy' in samples_vad_seg[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
6.354534
gamma total
8.399166999999998
coch1
3.111822
coch2
3.258550999999999
get avg
0.02742200000000139
fftfilter
6.883444999999998
gamma total
8.908110999999998
coch1
3.2317560000000007
coch2
3.2832630000000016
get avg
0.045344999999997526
fftfilter
4.172201999999999
gamma total
4.9787569999999945
coch1
1.837048000000003
coch2
2.3294479999999993
get avg
0.2546299999999988
fftfilter
4.9311679999999996
gamma total
5.864162999999998
coch1
1.7779260000000008
coch2
2.3948639999999983
get avg
0.27589500000000555
fftfilter
5.886939999999996
gamma total
7.699599999999997
coch1
3.265811999999997
coch2
3.277653000000001
get avg
0.02468600000000265
fftfilter
5.614539000000008
gamma total
7.400756999999999
coch1
2.749196000000012
coch2
3.2437069999999864
get avg
0.032976000000005
fftfilter
7.156456000000006
gamma total
9.620058999999998
coch1
3.315632000000008
coch2
3.4867849999999976
get avg
0.0642700000000076
fftfilter
7.044813000000005
gamma total
9.462448999999992
coch1
3.28141500

fftfilter
8.391836000000012
gamma total
10.613725000000045
coch1
3.320471999999995
coch2
3.3050799999999754
get avg
0.06076299999995172
fftfilter
8.59234200000003
gamma total
10.8204199999999
coch1
3.3038460000000214
coch2
3.3423119999999926
get avg
0.09399999999993724
fftfilter
7.287341999999967
gamma total
9.609599000000003
coch1
3.2903499999999894
coch2
3.3473840000000337
get avg
0.060910000000035325
fftfilter
4.0632479999999305
gamma total
4.89526699999999
coch1
1.8735880000000407
coch2
2.4649180000000115
get avg
0.37075500000003103
fftfilter
4.838039999999978
gamma total
5.694839000000002
coch1
1.7003069999999525
coch2
2.3748880000000554
get avg
0.36974099999997634
fftfilter
10.203662000000008
gamma total
12.902456000000143
coch1
3.4133049999998093
coch2
3.410639000000174
get avg
0.07679699999994227
fftfilter
9.406858000000057
gamma total
12.035261999999875
coch1
3.268026000000191
coch2
3.382498999999825
get avg
0.11384499999985565
fftfilter
6.427018000000089
gamma total
8.4443120

In [26]:
for i in range(0, len(samples_20)):
    deg = np.load(samples_vad_seg_20[i])
    if('npy' in samples_vad_seg_20[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_20[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
9.152417000000014
gamma total
11.88223199999993
coch1
3.346804999999904
coch2
3.4668830000000526
get avg
0.07738399999993817
fftfilter
9.38678600000003
gamma total
12.031563000000006
coch1
3.4095839999999953
coch2
3.4859190000001945
get avg
0.07761699999991833
fftfilter
50.013021999999864
gamma total
57.21774099999993
coch1
5.392274999999927
coch2
5.514114000000063
get avg
2.353701000000001
fftfilter
52.424441000000115
gamma total
59.654763
coch1
4.991905999999972
coch2
5.32849299999998
get avg
2.3396399999999176
fftfilter
10.001056000000062
gamma total
12.667568999999958
coch1
3.339811999999938
coch2
3.445998000000145
get avg
0.0750310000000809
fftfilter
8.428242999999839
gamma total
11.051389999999856
coch1
3.3344190000000253
coch2
3.4757560000000467
get avg
0.07712399999991248
fftfilter
8.87164800000005
gamma total
11.521169999999984
coch1
3.3409560000000056
coch2
3.4575310000000172
get avg
0.07632899999998699
fftfilter
8.8101079999999
gamma total
11.451706000000058
coch1


fftfilter
51.127296000000115
gamma total
58.361541000000216
coch1
5.149928999999702
coch2
5.3212610000000495
get avg
2.3466560000001664
fftfilter
9.80318299999999
gamma total
12.623257000000194
coch1
3.3455340000000433
coch2
3.462460000000192
get avg
0.1301589999998214
fftfilter
8.748000999999931
gamma total
11.617061999999805
coch1
3.3306769999999233
coch2
3.3941750000003594
get avg
0.07657899999958317
fftfilter
198.86699399999998
gamma total
207.7177029999998
coch1
12.628171000000293
coch2
12.982768999999735
get avg
3.7341519999999946
fftfilter
204.31948599999942
gamma total
213.5249920000001
coch1
13.936351999999715
coch2
15.712580000000344
get avg
3.6917700000003606
fftfilter
51.411433000000216
gamma total
58.58222300000034
coch1
4.931507000000238
coch2
5.297931999999491
get avg
2.3101210000004357
fftfilter
58.0015429999994
gamma total
65.47605699999986
coch1
5.072615000000042
coch2
5.428273999999874
get avg
2.3388029999996434
fftfilter
48.13233299999956
gamma total
55.612188000000

In [27]:
for i in range(0, len(samples_40)):
    deg = np.load(samples_vad_seg_40[i])
    if('npy' in samples_vad_seg_40[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_40[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
9.896442000000206
gamma total
12.626634000000195
coch1
3.365205999999489
coch2
3.399640999999974
get avg
0.07604900000023918
fftfilter
10.24108200000046
gamma total
13.10415600000033
coch1
3.4239529999995284
coch2
3.39009999999962
get avg
0.0737570000001142
fftfilter
9.724412000000484
gamma total
12.551504000000023
coch1
3.343966000000364
coch2
3.478092999999717
get avg
0.07790199999999459
fftfilter
9.474144000000706
gamma total
12.349076999999852
coch1
3.2967909999997573
coch2
3.3873190000003888
get avg
0.11142599999948288
fftfilter
11.060594000000492
gamma total
13.74478099999942
coch1
3.3458800000007614
coch2
3.449416999999812
get avg
0.10658299999977316
fftfilter
9.185637999999926
gamma total
12.028567000000294
coch1
3.3174989999997706
coch2
3.4525619999994888
get avg
0.07787699999971665
fftfilter
51.886741999999686
gamma total
59.15016900000046
coch1
5.129842000000281
coch2
5.406473000000005
get avg
2.3415839999997843
fftfilter
53.55815800000073
gamma total
60.9820789999

fftfilter
9.104521000000204
gamma total
11.931684000000132
coch1
3.2451109999992696
coch2
3.350615000000289
get avg
0.07576799999969808
fftfilter
53.68841100000009
gamma total
61.243586999999934
coch1
4.891480000000229
coch2
5.5541769999999815
get avg
2.352005000000645
fftfilter
52.17841599999974
gamma total
59.545822000000044
coch1
5.488957999999911
coch2
5.4482889999999315
get avg
2.338448999999855
fftfilter
9.082698999999593
gamma total
11.936263000000508
coch1
3.313199999999597
coch2
3.442804000000251
get avg
0.07234200000038982
fftfilter
9.521566000000348
gamma total
12.217230999999629
coch1
3.3809170000004087
coch2
3.438210000000254
get avg
0.07835599999998522
fftfilter
10.029411999999866
gamma total
12.647811000000729
coch1
3.336841999999706
coch2
3.4474350000000413
get avg
0.07909800000015821
fftfilter
8.111151999999493
gamma total
10.947583999999551
coch1
3.2880800000002637
coch2
3.4288269999997283
get avg
0.1062579999997979
fftfilter
12.394412999999986
gamma total
15.22878700

In [28]:
for i in range(0, len(samples_80)):
    deg = np.load(samples_vad_seg_80[i])
    if('npy' in samples_vad_seg_80[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_80[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
9.950256000000081
gamma total
12.606294000000162
coch1
3.426542999999583
coch2
3.5043380000006437
get avg
0.13924300000053336
fftfilter
9.679578999999649
gamma total
12.558517999999822
coch1
3.347751999999673
coch2
3.4248240000006263
get avg
0.11328799999955663
fftfilter
9.783644000000095
gamma total
12.42718799999966
coch1
3.3625010000005204
coch2
3.4730349999999817
get avg
0.07765999999992346
fftfilter
9.301806999999826
gamma total
11.947016000000076
coch1
3.369756000000052
coch2
3.4596670000000813
get avg
0.07364400000005844
fftfilter
10.324220999999852
gamma total
12.970421999999417
coch1
3.3480930000005173
coch2
3.4284969999998793
get avg
0.07797699999991892
fftfilter
9.1042809999999
gamma total
11.76689400000032
coch1
3.3162419999998747
coch2
3.4394920000004277
get avg
0.07329800000024989
fftfilter
48.66878600000018
gamma total
55.70727299999999
coch1
4.9462869999997565
coch2
6.177231000000575
get avg
2.3487489999997706
fftfilter
51.65690699999959
gamma total
59.0776379

fftfilter
186.52417699999933
gamma total
194.9015670000008
coch1
12.85607600000003
coch2
12.294170999999551
get avg
3.716261999999915
fftfilter
49.46170799999891
gamma total
56.79704000000129
coch1
5.050186999998914
coch2
5.558882999999696
get avg
2.2275320000007923
fftfilter
46.4163609999996
gamma total
53.677073000000746
coch1
5.17011199999979
coch2
5.521280999999362
get avg
2.2281519999996817
fftfilter
8.412599999999657
gamma total
11.046234999999797
coch1
3.346331000000646
coch2
3.4463849999992817
get avg
0.07481399999960558
fftfilter
9.261710999999195
gamma total
11.865639999999985
coch1
3.354332999999315
coch2
3.414071999999578
get avg
0.07317800000055286
fftfilter
9.537867999999435
gamma total
12.166221999999834
coch1
3.327541000000565
coch2
3.469747000001007
get avg
0.10591100000056031
fftfilter
9.375813999999082
gamma total
12.042062999998961
coch1
3.3626020000010612
coch2
3.4670749999986583
get avg
0.07491599999957543
fftfilter
9.356418999999732
gamma total
11.97756599999957


In [29]:
for i in range(0, len(samples_100)):
    deg = np.load(samples_vad_seg_100[i])
    if('npy' in samples_vad_seg_100[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_100[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
11.679008000000977
gamma total
14.356235000001107
coch1
3.3605509999997594
coch2
3.454030999999304
get avg
0.11156599999958416
fftfilter
9.891671999999744
gamma total
12.52703400000064
coch1
3.3836129999999685
coch2
3.4177339999987453
get avg
0.07578099999955157
fftfilter
9.584625999999844
gamma total
12.287215999998807
coch1
3.380114000001413
coch2
3.438931999999113
get avg
0.07510200000069744
fftfilter
8.620224000000235
gamma total
11.260564000000159
coch1
3.3394029999999475
coch2
3.4732920000005834
get avg
0.07358500000009371
fftfilter
8.785421999999016
gamma total
11.418002000000342
coch1
3.3549949999996898
coch2
3.5117340000015247
get avg
0.07352600000012899
fftfilter
8.836089999998876
gamma total
11.44184999999925
coch1
3.3443459999998595
coch2
3.4286250000004657
get avg
0.07481300000108604
fftfilter
49.20766999999978
gamma total
56.528942999999344
coch1
5.022447000001193
coch2
5.603020999998989
get avg
2.2054060000009486
fftfilter
49.73152200000004
gamma total
56.91682

get avg
3.715158999999403
fftfilter
180.88008400000035
gamma total
189.55011100000047
coch1
11.945878000000448
coch2
11.913528999999471
get avg
3.7075759999988804
fftfilter
47.98709599999893
gamma total
55.12574400000085
coch1
4.8427150000006804
coch2
5.391109999998662
get avg
2.297984999999244
fftfilter
48.91320900000028
gamma total
56.03924099999858
coch1
5.06158300000061
coch2
5.176509999999325
get avg
2.280972999998994
fftfilter
9.285072999999102
gamma total
11.895135999999184
coch1
3.2692709999992076
coch2
3.3891849999999977
get avg
0.07919199999923876
fftfilter
10.05010399999992
gamma total
12.693629000001238
coch1
3.385268999998516
coch2
3.4236610000007204
get avg
0.09691200000088429
fftfilter
10.079098000000158
gamma total
12.780114999999569
coch1
3.287470999999641
coch2
3.505293000000165
get avg
0.07787500000085856
fftfilter
9.014720999999554
gamma total
11.661557999999786
coch1
3.3463579999988724
coch2
3.3993980000013835
get avg
0.07636899999852176
fftfilter
9.21765200000118


In [30]:
for i in range(0, len(samples_140)):
    deg = np.load(samples_vad_seg_140[i])
    if('npy' in samples_vad_seg_140[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_140[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
9.47519199999806
gamma total
12.371488000000681
coch1
3.310349999999744
coch2
3.421296999997139
get avg
0.10486200000013923
fftfilter
9.93426200000249
gamma total
12.62416900000244
coch1
3.2617109999991953
coch2
3.3690299999980198
get avg
0.07519999999931315
fftfilter
9.614692999999534
gamma total
12.54113199999847
coch1
3.2376729999996314
coch2
3.309567000000243
get avg
0.11383500000010827
fftfilter
9.869588999998086
gamma total
12.558332000000519
coch1
3.345358999999007
coch2
3.400348999999551
get avg
0.07486099999732687
fftfilter
8.772468999999546
gamma total
11.409058000001096
coch1
3.316925999999512
coch2
3.509297999997216
get avg
0.077476000002207
fftfilter
9.320832999997947
gamma total
12.151181999997789
coch1
3.3496930000001157
coch2
3.512209000000439
get avg
0.10841000000073109
fftfilter
50.717225000000326
gamma total
58.04855300000054
coch1
4.8880280000012135
coch2
6.000527000000147
get avg
2.242635999999038
fftfilter
45.655148000001645
gamma total
52.92340899999908

gamma total
198.75654900000154
coch1
12.455887000000075
coch2
15.226385999998456
get avg
3.669052000001102
fftfilter
48.828325999998924
gamma total
56.03464099999837
coch1
4.921364000001631
coch2
5.560582999998587
get avg
2.1851370000003953
fftfilter
48.31842699999834
gamma total
55.68008900000132
coch1
5.06954499999847
coch2
5.834759000001213
get avg
2.3551410000000033
fftfilter
9.195549000000028
gamma total
11.84186899999986
coch1
3.3387609999990673
coch2
3.4417910000011034
get avg
0.1084709999995539
fftfilter
9.811025999999401
gamma total
12.597729000000982
coch1
3.3655709999984538
coch2
3.675814000001992
get avg
0.07530000000042492
fftfilter
10.0658549999971
gamma total
12.65125800000169
coch1
3.30638899999758
coch2
3.4672540000028675
get avg
0.07699499999944237
fftfilter
9.568794000002526
gamma total
12.3919739999983
coch1
3.366178000000218
coch2
3.4413100000019767
get avg
0.0740509999995993
fftfilter
8.628751000000193
gamma total
11.23189800000182
coch1
3.387321999998676
coch2
3.

In [31]:
for i in range(0, len(samples_160)):
    deg = np.load(samples_vad_seg_160[i])
    if('npy' in samples_vad_seg_160[i].split('/')[-1]):
        label = deg[0]
    else:
        label = deg["label"]
        
    mrcg_L, mrcg_R = mrcg_transpose(samples_160[i])
    mrcg_L_stack, label_array = generate_instances(mrcg_L, 100, 10, label)
    mrcg_R_stack, label_array = generate_instances(mrcg_R, 100, 10, label)
    
    mrcg_L_tensor.append(mrcg_L_stack)
    mrcg_R_tensor.append(mrcg_R_stack)
    label_list.append(label_array)

fftfilter
191.720567999997
gamma total
200.35592600000018
coch1
13.27791299999808
coch2
13.43369900000107
get avg
3.6874940000016068
fftfilter
188.65200299999924
gamma total
197.22329399999944
coch1
12.325831999998627
coch2
12.826532999999472
get avg
3.6360210000020743
fftfilter
47.743163999999524
gamma total
54.88219399999798
coch1
5.618768000000273
coch2
5.380606999999145
get avg
2.210566999998264
fftfilter
49.39583800000037
gamma total
56.72142999999778
coch1
5.5231160000003
coch2
5.554855999998836
get avg
2.354254999998375
fftfilter
8.466154000001552
gamma total
11.073459000002913
coch1
3.3435799999970186
coch2
3.441922000001796
get avg
0.07546100000035949
fftfilter
9.639014999997016
gamma total
12.209876999997505
coch1
3.349149000001489
coch2
3.628951999999117
get avg
0.07315900000321562
fftfilter
9.233156999998755
gamma total
11.866821999999956
coch1
3.3236109999998007
coch2
3.456670999999915
get avg
0.07540099999823724
fftfilter
8.54067700000087
gamma total
11.17460199999914
coc

fftfilter
11.22584000000279
gamma total
13.889581999999791
coch1
3.3829210000003513
coch2
3.497486000000208
get avg
0.09881099999984144
fftfilter
195.66835899999933
gamma total
204.29866700000275
coch1
13.943443000000116
coch2
12.8482649999969
get avg
3.6575750000010885
fftfilter
189.25487799999974
gamma total
198.03577700000096
coch1
12.607427999999345
coch2
13.748569000003044
get avg
3.605214999999589
fftfilter
47.88486499999999
gamma total
54.87639200000194
coch1
4.920145000000048
coch2
5.4727380000003905
get avg
2.3166720000008354
fftfilter
48.620990999999776
gamma total
55.686014000002615
coch1
4.888290999999299
coch2
5.456615999999485
get avg
2.238915999998426
fftfilter
46.036731999996846
gamma total
53.08512899999914
coch1
4.910391000001255
coch2
5.5306700000001
get avg
2.261958000002778
fftfilter
49.9716789999984
gamma total
57.10791699999754
coch1
5.6550050000005285
coch2
5.479020999999193
get avg
2.2287880000003497
fftfilter
49.3975070000015
gamma total
56.53310599999895
coch

In [32]:
mrcg_L_tensor[0].shape

(19, 768, 100, 1)

In [33]:
n_20 = 50 + len(samples_20)
n_40 = n_20 + len(samples_40)
n_80 = n_40 + len(samples_80)
n_100 = n_80 + len(samples_100)
n_140 = n_100 + len(samples_140)
n_160 = n_140 + len(samples_160)

In [34]:
total_instances_tensor = []

for i in range(0, n_160):
    concat_tensor = np.concatenate([mrcg_L_tensor[i], mrcg_R_tensor[i]], axis=-1)
    total_instances_tensor.append(concat_tensor)

In [35]:
total_instances_tensor[0].shape

(19, 768, 100, 2)

In [36]:
total_label = []

for i in range(0, n_160):
    array_label = np.array(label_list[i])
    total_label.append(array_label)

In [37]:
# np.savez('MRCG_data', total_instances_tensor=total_instances_tensor, total_label=total_label)

In [38]:
vad_label = []

for i in range(0, n_160):
    array_label = np.array(label_list[i])
    vad_label.append(array_label)

In [39]:
for i in range(0, n_160):
    print(total_instances_tensor[i].shape, total_label[i].shape)

(19, 768, 100, 2) (19,)
(6, 768, 100, 2) (6,)
(16, 768, 100, 2) (16,)
(24, 768, 100, 2) (24,)
(14, 768, 100, 2) (14,)
(15, 768, 100, 2) (15,)
(33, 768, 100, 2) (33,)
(21, 768, 100, 2) (21,)
(9, 768, 100, 2) (9,)
(19, 768, 100, 2) (19,)
(16, 768, 100, 2) (16,)
(28, 768, 100, 2) (28,)
(20, 768, 100, 2) (20,)
(24, 768, 100, 2) (24,)
(22, 768, 100, 2) (22,)
(30, 768, 100, 2) (30,)
(17, 768, 100, 2) (17,)
(14, 768, 100, 2) (14,)
(23, 768, 100, 2) (23,)
(30, 768, 100, 2) (30,)
(6, 768, 100, 2) (6,)
(17, 768, 100, 2) (17,)
(22, 768, 100, 2) (22,)
(23, 768, 100, 2) (23,)
(18, 768, 100, 2) (18,)
(10, 768, 100, 2) (10,)
(22, 768, 100, 2) (22,)
(15, 768, 100, 2) (15,)
(21, 768, 100, 2) (21,)
(25, 768, 100, 2) (25,)
(23, 768, 100, 2) (23,)
(23, 768, 100, 2) (23,)
(9, 768, 100, 2) (9,)
(30, 768, 100, 2) (30,)
(20, 768, 100, 2) (20,)
(14, 768, 100, 2) (14,)
(21, 768, 100, 2) (21,)
(16, 768, 100, 2) (16,)
(13, 768, 100, 2) (13,)
(29, 768, 100, 2) (29,)
(47, 768, 100, 2) (47,)
(31, 768, 100, 2) (31,)


In [40]:
val = 0
for i in range(0, n_160):
    val = val + total_instances_tensor[i].shape[0]
    
val

32983

In [41]:
for i in range(0, 12):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -90

for i in range(12, 25):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -30
            
for i in range(25, 38):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 30
            
for i in range(38, 50):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 90
            
for i in range(50, n_20):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -70

for i in range(n_20, n_40):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -50
            
for i in range(n_40, n_80):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -10
            
for i in range(n_80, n_100):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 10
            
for i in range(n_100, n_140):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 50
            
for i in range(n_140, n_160):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 70
              
total_label

[array([-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90., -90., -90., -90., -90., -90., -90., -90.]),
 array([-90., -90., -90., -90., -90., -90.]),
 array([  0.,   0.,   0.,   0.,   0.,   0.,   0., -90., -90., -90., -90.,
        -90., -90., -90., -90., -90.]),
 array([-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
          0.,   0.]),
 array([-90., -90., -90., -90., -90., -90., -90., -90.,   0.,   0.,   0.,
          0.,   0.,   0.]),
 array([-90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90., -90., -90.,   0.]),
 array([  0.,   0.,   0.,   0.,   0.,   0.,   0., -90., -90., -90., -90.,
        -90., -90., -90., -90., -90., -90., -90., -90., -90., -90., -90.,
        -90., -90., -90., -90., -90., -90., -90., -90., -90.,   0.,   0.]),
 array([  0.,   0.,   0.,   0.,   0., -90., -90., -90., -90., -90., -90.,
        -90., -90., -90., -90.

In [42]:
np.random.seed(19)
idx = np.random.permutation(n_160)
idx

array([ 23,   8, 258, 138, 199, 145, 234, 211, 253, 101, 135, 284, 148,
        48,  12,  75, 179, 209,  61,  90, 243,   1, 229,  27,  36, 142,
        60, 103, 302, 121,  92, 210,  24,  15,  49,   2,  65,   6,  17,
        95, 165, 259,  98, 257, 190, 177,  37, 197, 255, 120,  64,  13,
       187, 227, 290, 285, 141, 281, 132, 168,  62, 251, 207, 223, 174,
       205, 216,  96, 119, 144,  20, 117, 171, 252, 249, 175,  86, 154,
       156, 296, 304, 184, 137, 200, 222, 300, 192, 272,  16, 176, 149,
       208, 129, 306,  87, 289, 250,  78, 143,  74, 113, 279, 276,  54,
       189, 136,  40, 139, 283, 128, 270, 160, 241, 288, 150, 185, 278,
       214, 181,  33,  66,  10, 217, 297, 230, 235, 158, 202,  11,  45,
        41,  26,  31, 312,  34, 146,  91, 277,  57, 237, 108,  71, 161,
       178, 115,  30,  35,  72, 254, 307,  50, 163, 293,  82,   7, 294,
        42,  58, 180,  14, 314, 130, 219, 238, 186,  59, 299, 280,  70,
        81, 261,  83, 164, 242, 155,  89, 204, 292, 236, 104, 15

In [43]:
X = []
y = []
vad = []

for i in range(0, n_160):
    X.append(total_instances_tensor[idx[i]])
    y.append(total_label[idx[i]])
    vad.append(vad_label[idx[i]])

In [44]:
for i in range(0, n_160):
    print(X[i].shape[0], y[i].shape, vad[i].shape)

23 (23,) (23,)
9 (9,) (9,)
191 (191,) (191,)
191 (191,) (191,)
191 (191,) (191,)
30 (30,) (30,)
191 (191,) (191,)
30 (30,) (30,)
793 (793,) (793,)
30 (30,) (30,)
191 (191,) (191,)
30 (30,) (30,)
191 (191,) (191,)
20 (20,) (20,)
20 (20,) (20,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
191 (191,) (191,)
30 (30,) (30,)
6 (6,) (6,)
30 (30,) (30,)
15 (15,) (15,)
21 (21,) (21,)
191 (191,) (191,)
191 (191,) (191,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
191 (191,) (191,)
191 (191,) (191,)
18 (18,) (18,)
30 (30,) (30,)
18 (18,) (18,)
16 (16,) (16,)
191 (191,) (191,)
33 (33,) (33,)
14 (14,) (14,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
793 (793,) (793,)
16 (16,) (16,)
191 (191,) (191,)
30 (30,) (30,)
30 (30,) (30,)
191 (191,) (191,)
24 (24,) (24,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
30 (30,) (30,)
191 (191,) (191,)
191 (191,) (191,)
30 (30,) (30,)
191 (191,) (191,)
30 (30,) (30,)
191 (191,) (191,)
191 (191,) (191,

In [45]:
train_idx = n_160
X_train = np.concatenate(X[:train_idx], axis=0)
y_train = np.concatenate(y[:train_idx], axis=0)
vad_train = np.concatenate(vad[:train_idx], axis=0)

X_train.shape, y_train.shape, vad_train.shape

((32983, 768, 100, 2), (32983,), (32983,))

# Regression

In [46]:
from keras.layers import Conv2D, MaxPooling2D, Input, Flatten, Dropout, Dense, Reshape, Conv1D
from keras.models import Model

input_spectrogram = Input(shape=(X_train.shape[1], X_train.shape[2], X_train.shape[3]))

conv_1 = Conv2D(16, (3, 3), activation='relu')(input_spectrogram)
max_pool_1 = MaxPooling2D((2, 2))(conv_1)

conv_2 = Conv2D(32, (3, 3), activation='relu')(max_pool_1)
max_pool_2 = MaxPooling2D((2, 2))(conv_2)

conv_3 = Conv2D(64, (3, 3), strides=(2,1), activation='relu')(max_pool_2)
conv_3_1 = Conv2D(64, (3, 2), strides=(2,1), activation='relu')(conv_3)
max_pool_3 = MaxPooling2D((3, 2), name='max_pool_3')(conv_3_1)

shape_max_pool_3 = max_pool_3.get_shape().as_list()    # (None, height, width, channel)
print("shape_max_pool_3 : ", shape_max_pool_3)
# reshaped = layers.Reshape((-1, shape_list[1]*shape_list[3]))(max_pool_3)

conv_4 = Conv2D(1024, (shape_max_pool_3[1], 1), padding='valid', activation='relu')(max_pool_3)
shape_conv_4 = conv_4.get_shape().as_list()
print("shape_conv_4 : ", shape_conv_4)

reshaped = Reshape((shape_conv_4[2], shape_conv_4[3]))(conv_4) # reshape to (timesteps, features) explicitly 

conv_5 = Conv1D(512, kernel_size=3, activation='relu')(reshaped)

flatten = Flatten()(conv_5)
# flatten_drop = Dropout(0.3)(flatten)

fc1 = Dense(32, activation='relu')(flatten)
fc1_drop = Dropout(0.1)(fc1)

vad_out = Dense(1, activation='sigmoid', name='vad_output')(fc1_drop)
dense_out = Dense(1, activation='linear', name='reg_output')(fc1_drop)


model_reg = Model(inputs=input_spectrogram, outputs=[vad_out, dense_out])
model_reg.summary()

Using TensorFlow backend.


shape_max_pool_3 :  [None, 15, 10, 64]
shape_conv_4 :  [None, 1, 10, 1024]
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 768, 100, 2)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 766, 98, 16)  304         input_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 383, 49, 16)  0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 381, 47, 32)  4640        max_pooling2d_1[0][0]            
__________________________________

In [47]:
from keras.utils import multi_gpu_model

model_reg = multi_gpu_model(model_reg, gpus=8, cpu_relocation=True)

In [49]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

model_reg.compile(optimizer ='rmsprop', loss={'vad_output' : 'binary_crossentropy', 'reg_output' : 'mse'},
              metrics ={'vad_output' : 'acc', 'reg_output' : 'mse'})

callbacks_list = [EarlyStopping(monitor='loss', patience=20),
                 ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10)]

history = model_reg.fit(X_train, [vad_train, y_train],
                    epochs=150, batch_size=64, 
                    callbacks=callbacks_list,
                    shuffle=True)

Epoch 1/150
32983/32983 [==============================] - 63s 2ms/step - loss: 229.4382 - vad_output_loss: 0.4720 - reg_output_loss: 228.9662 - vad_output_acc: 0.8905 - reg_output_mean_squared_error: 228.9662
Epoch 2/150
32983/32983 [==============================] - 67s 2ms/step - loss: 90.8110 - vad_output_loss: 0.1797 - reg_output_loss: 90.6313 - vad_output_acc: 0.9496 - reg_output_mean_squared_error: 90.6313
Epoch 3/150
32983/32983 [==============================] - 74s 2ms/step - loss: 64.0375 - vad_output_loss: 0.1551 - reg_output_loss: 63.8824 - vad_output_acc: 0.9543 - reg_output_mean_squared_error: 63.8824
Epoch 4/150
32983/32983 [==============================] - 73s 2ms/step - loss: 49.0225 - vad_output_loss: 0.1189 - reg_output_loss: 48.9036 - vad_output_acc: 0.9635 - reg_output_mean_squared_error: 48.9036
Epoch 5/150
32983/32983 [==============================] - 73s 2ms/step - loss: 43.2567 - vad_output_loss: 0.1110 - reg_output_loss: 43.1457 - vad_output_acc: 0.9695 - r

32983/32983 [==============================] - 75s 2ms/step - loss: 9.9621 - vad_output_loss: 0.0129 - reg_output_loss: 9.9492 - vad_output_acc: 0.9981 - reg_output_mean_squared_error: 9.9492
Epoch 41/150
32983/32983 [==============================] - 75s 2ms/step - loss: 10.4007 - vad_output_loss: 0.0131 - reg_output_loss: 10.3876 - vad_output_acc: 0.9981 - reg_output_mean_squared_error: 10.3876
Epoch 42/150
32983/32983 [==============================] - 74s 2ms/step - loss: 10.1274 - vad_output_loss: 0.0146 - reg_output_loss: 10.1127 - vad_output_acc: 0.9980 - reg_output_mean_squared_error: 10.1127
Epoch 43/150
32983/32983 [==============================] - 74s 2ms/step - loss: 10.0992 - vad_output_loss: 0.0079 - reg_output_loss: 10.0913 - vad_output_acc: 0.9986 - reg_output_mean_squared_error: 10.0913
Epoch 44/150
32983/32983 [==============================] - 74s 2ms/step - loss: 9.4692 - vad_output_loss: 0.0075 - reg_output_loss: 9.4617 - vad_output_acc: 0.9987 - reg_output_mean_s

32983/32983 [==============================] - 74s 2ms/step - loss: 4.9325 - vad_output_loss: 4.5843e-04 - reg_output_loss: 4.9320 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.9320
Epoch 80/150
32983/32983 [==============================] - 74s 2ms/step - loss: 4.7790 - vad_output_loss: 4.8686e-04 - reg_output_loss: 4.7785 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.7785
Epoch 81/150
32983/32983 [==============================] - 74s 2ms/step - loss: 4.7813 - vad_output_loss: 3.9293e-04 - reg_output_loss: 4.7809 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.7809
Epoch 82/150
32983/32983 [==============================] - 74s 2ms/step - loss: 4.8943 - vad_output_loss: 3.8477e-04 - reg_output_loss: 4.8939 - vad_output_acc: 1.0000 - reg_output_mean_squared_error: 4.8939
Epoch 83/150
32983/32983 [==============================] - 73s 2ms/step - loss: 4.5710 - vad_output_loss: 3.6355e-04 - reg_output_loss: 4.5706 - vad_output_acc: 1.0000 - reg_ou

32983/32983 [==============================] - 73s 2ms/step - loss: 4.5310 - vad_output_loss: 3.7733e-04 - reg_output_loss: 4.5306 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.5306
Epoch 119/150
32983/32983 [==============================] - 73s 2ms/step - loss: 4.5280 - vad_output_loss: 3.4367e-04 - reg_output_loss: 4.5277 - vad_output_acc: 1.0000 - reg_output_mean_squared_error: 4.5277


In [50]:
model_reg.save('MRCG_2DCNN_1DCNN_regression_multi.h5')

# Classification

In [51]:
total_label = []

for i in range(0, n_160):
    array_label = np.array(label_list[i])
    total_label.append(array_label)

In [52]:
vad_label = []

for i in range(0, n_160):
    array_label = np.array(label_list[i])
    vad_label.append(array_label)

In [53]:
for i in range(0, 12):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 1

for i in range(12, 25):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 4
            
for i in range(25, 38):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 7
            
for i in range(38, 50):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 10
            
for i in range(50, n_20):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 2

for i in range(n_20, n_40):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 3
            
for i in range(n_40, n_80):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 5
            
for i in range(n_80, n_100):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 6
            
for i in range(n_100, n_140):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 8
            
for i in range(n_140, n_160):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 9
              
total_label

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]),
 array([1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
      

In [54]:
np.random.seed(19)
idx = np.random.permutation(n_160)
idx

array([ 23,   8, 258, 138, 199, 145, 234, 211, 253, 101, 135, 284, 148,
        48,  12,  75, 179, 209,  61,  90, 243,   1, 229,  27,  36, 142,
        60, 103, 302, 121,  92, 210,  24,  15,  49,   2,  65,   6,  17,
        95, 165, 259,  98, 257, 190, 177,  37, 197, 255, 120,  64,  13,
       187, 227, 290, 285, 141, 281, 132, 168,  62, 251, 207, 223, 174,
       205, 216,  96, 119, 144,  20, 117, 171, 252, 249, 175,  86, 154,
       156, 296, 304, 184, 137, 200, 222, 300, 192, 272,  16, 176, 149,
       208, 129, 306,  87, 289, 250,  78, 143,  74, 113, 279, 276,  54,
       189, 136,  40, 139, 283, 128, 270, 160, 241, 288, 150, 185, 278,
       214, 181,  33,  66,  10, 217, 297, 230, 235, 158, 202,  11,  45,
        41,  26,  31, 312,  34, 146,  91, 277,  57, 237, 108,  71, 161,
       178, 115,  30,  35,  72, 254, 307,  50, 163, 293,  82,   7, 294,
        42,  58, 180,  14, 314, 130, 219, 238, 186,  59, 299, 280,  70,
        81, 261,  83, 164, 242, 155,  89, 204, 292, 236, 104, 15

In [55]:
X = []
y = []
vad = []

for i in range(0, n_160):
    X.append(total_instances_tensor[idx[i]])
    y.append(total_label[idx[i]])
    vad.append(vad_label[idx[i]])

In [56]:
train_idx = n_160
X_train = np.concatenate(X[:train_idx], axis=0)
y_train = np.concatenate(y[:train_idx], axis=0)
vad_train = np.concatenate(vad[:train_idx], axis=0)

X_train.shape, y_train.shape, vad_train.shape

((32983, 768, 100, 2), (32983,), (32983,))

In [57]:
from keras.utils import np_utils

y_train = np_utils.to_categorical(y_train, 11)

In [58]:
from keras.layers import Conv2D, MaxPooling2D, Input, Flatten, Dropout, Dense, Reshape, Conv1D
from keras.models import Model

input_spectrogram = Input(shape=(X_train.shape[1], X_train.shape[2], X_train.shape[3]))

conv_1 = Conv2D(16, (3, 3), activation='relu')(input_spectrogram)
max_pool_1 = MaxPooling2D((2, 2))(conv_1)

conv_2 = Conv2D(32, (3, 3), activation='relu')(max_pool_1)
max_pool_2 = MaxPooling2D((2, 2))(conv_2)

conv_3 = Conv2D(64, (3, 3), strides=(2,1), activation='relu')(max_pool_2)
conv_3_1 = Conv2D(64, (3, 2), strides=(2,1), activation='relu')(conv_3)
max_pool_3 = MaxPooling2D((3, 2), name='max_pool_3')(conv_3_1)

shape_max_pool_3 = max_pool_3.get_shape().as_list()    # (None, height, width, channel)
print("shape_max_pool_3 : ", shape_max_pool_3)
# reshaped = layers.Reshape((-1, shape_list[1]*shape_list[3]))(max_pool_3)

conv_4 = Conv2D(1024, (shape_max_pool_3[1], 1), padding='valid', activation='relu')(max_pool_3)
shape_conv_4 = conv_4.get_shape().as_list()
print("shape_conv_4 : ", shape_conv_4)

reshaped = Reshape((shape_conv_4[2], shape_conv_4[3]))(conv_4) # reshape to (timesteps, features) explicitly 

conv_5 = Conv1D(512, kernel_size=3, activation='relu')(reshaped)

flatten = Flatten()(conv_5)
# flatten_drop = Dropout(0.3)(flatten)

fc1 = Dense(32, activation='relu')(flatten)
fc1_drop = Dropout(0.1)(fc1)

vad_out = Dense(1, activation='sigmoid', name='vad_output')(fc1_drop)
dense_out = Dense(11, activation='softmax', name='clf_output')(fc1_drop)

model_clf = Model(inputs=input_spectrogram, outputs=[vad_out, dense_out])
model_clf.summary()

shape_max_pool_3 :  [None, 15, 10, 64]
shape_conv_4 :  [None, 1, 10, 1024]
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 768, 100, 2)  0                                            
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 766, 98, 16)  304         input_2[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)  (None, 383, 49, 16)  0           conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 381, 47, 32)  4640        max_pooling2d_3[0][0]            
__________________________________

In [59]:
from keras.utils import multi_gpu_model

model_clf = multi_gpu_model(model_clf, gpus=8, cpu_relocation=True)

In [60]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

model_clf.compile(optimizer ='rmsprop', loss={'vad_output' : 'binary_crossentropy', 'clf_output' : 'categorical_crossentropy'},
              metrics ={'vad_output' : 'acc', 'clf_output' : 'acc'})

model_path = 'MRCG_2DCNN_1DCNN_clf_multi.h5'
callbacks_list = [EarlyStopping(monitor='loss', patience=20),
                 ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10),
                 ModelCheckpoint(filepath=model_path, monitor='loss', verbose=1, save_best_only=True)]

history = model_clf.fit(X_train, [vad_train, y_train],
                    epochs=150, batch_size=64, 
                    callbacks=callbacks_list,
                    shuffle=True)

Epoch 1/150
32983/32983 [==============================] - 68s 2ms/step - loss: 0.6116 - vad_output_loss: 0.1393 - clf_output_loss: 0.4723 - vad_output_acc: 0.9539 - clf_output_acc: 0.8567

Epoch 00001: loss improved from inf to 0.61160, saving model to MRCG_2DCNN_1DCNN_clf_multi.h5
Epoch 2/150
32983/32983 [==============================] - 62s 2ms/step - loss: 0.2743 - vad_output_loss: 0.0383 - clf_output_loss: 0.2359 - vad_output_acc: 0.9862 - clf_output_acc: 0.9153

Epoch 00002: loss improved from 0.61160 to 0.27426, saving model to MRCG_2DCNN_1DCNN_clf_multi.h5
Epoch 3/150
32983/32983 [==============================] - 52s 2ms/step - loss: 0.1878 - vad_output_loss: 0.0315 - clf_output_loss: 0.1562 - vad_output_acc: 0.9887 - clf_output_acc: 0.9461

Epoch 00003: loss improved from 0.27426 to 0.18779, saving model to MRCG_2DCNN_1DCNN_clf_multi.h5
Epoch 4/150
32983/32983 [==============================] - 52s 2ms/step - loss: 0.1329 - vad_output_loss: 0.0227 - clf_output_loss: 0.1103 -

32983/32983 [==============================] - 53s 2ms/step - loss: 0.0121 - vad_output_loss: 0.0019 - clf_output_loss: 0.0102 - vad_output_acc: 0.9997 - clf_output_acc: 0.9988

Epoch 00032: loss did not improve from 0.00973
Epoch 33/150
32983/32983 [==============================] - 53s 2ms/step - loss: 0.0091 - vad_output_loss: 0.0025 - clf_output_loss: 0.0066 - vad_output_acc: 0.9996 - clf_output_acc: 0.9990

Epoch 00033: loss improved from 0.00973 to 0.00913, saving model to MRCG_2DCNN_1DCNN_clf_multi.h5
Epoch 34/150
32983/32983 [==============================] - 53s 2ms/step - loss: 0.0144 - vad_output_loss: 0.0029 - clf_output_loss: 0.0115 - vad_output_acc: 0.9996 - clf_output_acc: 0.9985

Epoch 00034: loss did not improve from 0.00913
Epoch 35/150
32983/32983 [==============================] - 53s 2ms/step - loss: 0.0120 - vad_output_loss: 0.0037 - clf_output_loss: 0.0083 - vad_output_acc: 0.9997 - clf_output_acc: 0.9990

Epoch 00035: loss did not improve from 0.00913
Epoch 36/1

32983/32983 [==============================] - 53s 2ms/step - loss: 0.0066 - vad_output_loss: 0.0016 - clf_output_loss: 0.0050 - vad_output_acc: 0.9997 - clf_output_acc: 0.9993

Epoch 00065: loss did not improve from 0.00488
Epoch 66/150
32983/32983 [==============================] - 54s 2ms/step - loss: 0.0065 - vad_output_loss: 9.8551e-04 - clf_output_loss: 0.0055 - vad_output_acc: 0.9999 - clf_output_acc: 0.9993

Epoch 00066: loss did not improve from 0.00488
Epoch 67/150
32983/32983 [==============================] - 53s 2ms/step - loss: 0.0051 - vad_output_loss: 0.0016 - clf_output_loss: 0.0035 - vad_output_acc: 0.9998 - clf_output_acc: 0.9995

Epoch 00067: loss did not improve from 0.00488
Epoch 68/150
32983/32983 [==============================] - 53s 2ms/step - loss: 0.0055 - vad_output_loss: 5.8864e-04 - clf_output_loss: 0.0049 - vad_output_acc: 0.9999 - clf_output_acc: 0.9994

Epoch 00068: loss did not improve from 0.00488
Epoch 69/150
32983/32983 [===========================

In [61]:
# model_clf.save('MRCG_2DCNN_1DCNN_clf_multi.h5')