In [1]:
import glob
import os
import librosa
import librosa.display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import specgram
import tensorflow as tf
import scipy.io.wavfile
import wave
import time

%matplotlib inline
plt.style.use('ggplot')


plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = 'Ubuntu'
plt.rcParams['font.monospace'] = 'Ubuntu Mono'
plt.rcParams['font.size'] = 12
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 11
plt.rcParams['figure.titlesize'] = 13 

In [2]:
sample_vad_seg_repo = os.path.join('.', 'Data', 'binary_segment')
samples_vad_seg = glob.glob(os.path.join(sample_vad_seg_repo, '*[npy|npz]'), recursive=True)

samples_vad_seg = sorted(samples_vad_seg)   
print(len(samples_vad_seg))

50


In [3]:
sample_vad_seg_repo_20 = os.path.join('.', 'Data', 'binary_segment', '20도')
samples_vad_seg_20 = glob.glob(os.path.join(sample_vad_seg_repo_20, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_20 = sorted(samples_vad_seg_20)   
print(len(samples_vad_seg_20))

36


In [4]:
sample_vad_seg_repo_40 = os.path.join('.', 'Data', 'binary_segment', '40도')
samples_vad_seg_40 = glob.glob(os.path.join(sample_vad_seg_repo_40, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_40 = sorted(samples_vad_seg_40)   
print(len(samples_vad_seg_40))

39


In [5]:
sample_vad_seg_repo_80 = os.path.join('.', 'Data', 'binary_segment', '80도')
samples_vad_seg_80 = glob.glob(os.path.join(sample_vad_seg_repo_80, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_80 = sorted(samples_vad_seg_80)   
print(len(samples_vad_seg_80))

47


In [6]:
sample_vad_seg_repo_100 = os.path.join('.', 'Data', 'binary_segment', '100도')
samples_vad_seg_100 = glob.glob(os.path.join(sample_vad_seg_repo_100, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_100 = sorted(samples_vad_seg_100)   
print(len(samples_vad_seg_100))

51


In [7]:
sample_vad_seg_repo_140 = os.path.join('.', 'Data', 'binary_segment', '140도')
samples_vad_seg_140 = glob.glob(os.path.join(sample_vad_seg_repo_140, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_140 = sorted(samples_vad_seg_140)   
print(len(samples_vad_seg_140))

41


In [8]:
sample_vad_seg_repo_160 = os.path.join('.', 'Data', 'binary_segment', '160도')
samples_vad_seg_160 = glob.glob(os.path.join(sample_vad_seg_repo_160, '**', '*[npy|npz]'), recursive=True)

samples_vad_seg_160 = sorted(samples_vad_seg_160)   
print(len(samples_vad_seg_160))

51


In [9]:
list(enumerate(samples_vad_seg))

[(0, './Data/binary_segment/01.npy'),
 (1, './Data/binary_segment/02.npy'),
 (2, './Data/binary_segment/03.npy'),
 (3, './Data/binary_segment/04.npy'),
 (4, './Data/binary_segment/05.npy'),
 (5, './Data/binary_segment/06.npy'),
 (6, './Data/binary_segment/07.npy'),
 (7, './Data/binary_segment/08.npy'),
 (8, './Data/binary_segment/09.npy'),
 (9, './Data/binary_segment/10.npy'),
 (10, './Data/binary_segment/11.npy'),
 (11, './Data/binary_segment/12.npy'),
 (12, './Data/binary_segment/13.npy'),
 (13, './Data/binary_segment/14.npy'),
 (14, './Data/binary_segment/15.npy'),
 (15, './Data/binary_segment/16.npy'),
 (16, './Data/binary_segment/17.npy'),
 (17, './Data/binary_segment/18.npy'),
 (18, './Data/binary_segment/19.npy'),
 (19, './Data/binary_segment/20.npy'),
 (20, './Data/binary_segment/21.npy'),
 (21, './Data/binary_segment/22.npy'),
 (22, './Data/binary_segment/23.npy'),
 (23, './Data/binary_segment/24.npy'),
 (24, './Data/binary_segment/25.npy'),
 (25, './Data/binary_segment/26.npy

In [10]:
list(enumerate(samples_vad_seg_20))

[(0, './Data/binary_segment/20도/output00.npz'),
 (1, './Data/binary_segment/20도/output01.npz'),
 (2, './Data/binary_segment/20도/output02.npz'),
 (3, './Data/binary_segment/20도/output03.npz'),
 (4, './Data/binary_segment/20도/output04.npz'),
 (5, './Data/binary_segment/20도/output05.npz'),
 (6, './Data/binary_segment/20도/output06.npz'),
 (7, './Data/binary_segment/20도/output07.npz'),
 (8, './Data/binary_segment/20도/output08.npz'),
 (9, './Data/binary_segment/20도/output09.npz'),
 (10, './Data/binary_segment/20도/output10.npz'),
 (11, './Data/binary_segment/20도/output11.npz'),
 (12, './Data/binary_segment/20도/output12.npz'),
 (13, './Data/binary_segment/20도/output13.npz'),
 (14, './Data/binary_segment/20도/output14.npz'),
 (15, './Data/binary_segment/20도/output15.npz'),
 (16, './Data/binary_segment/20도/output16.npz'),
 (17, './Data/binary_segment/20도/output17.npz'),
 (18, './Data/binary_segment/20도/output18.npz'),
 (19, './Data/binary_segment/20도/output19.npz'),
 (20, './Data/binary_segment/2

In [11]:
list(enumerate(samples_vad_seg_40))

[(0, './Data/binary_segment/40도/output00.npz'),
 (1, './Data/binary_segment/40도/output01.npz'),
 (2, './Data/binary_segment/40도/output02.npz'),
 (3, './Data/binary_segment/40도/output03.npz'),
 (4, './Data/binary_segment/40도/output04.npz'),
 (5, './Data/binary_segment/40도/output05.npz'),
 (6, './Data/binary_segment/40도/output06.npz'),
 (7, './Data/binary_segment/40도/output07.npz'),
 (8, './Data/binary_segment/40도/output08.npz'),
 (9, './Data/binary_segment/40도/output09.npz'),
 (10, './Data/binary_segment/40도/output10.npz'),
 (11, './Data/binary_segment/40도/output11.npz'),
 (12, './Data/binary_segment/40도/output12.npz'),
 (13, './Data/binary_segment/40도/output13.npz'),
 (14, './Data/binary_segment/40도/output14.npz'),
 (15, './Data/binary_segment/40도/output15.npz'),
 (16, './Data/binary_segment/40도/output16.npz'),
 (17, './Data/binary_segment/40도/output17.npz'),
 (18, './Data/binary_segment/40도/output18.npz'),
 (19, './Data/binary_segment/40도/output19.npz'),
 (20, './Data/binary_segment/4

In [12]:
list(enumerate(samples_vad_seg_80))

[(0, './Data/binary_segment/80도/output00.npz'),
 (1, './Data/binary_segment/80도/output01.npz'),
 (2, './Data/binary_segment/80도/output02.npz'),
 (3, './Data/binary_segment/80도/output03.npz'),
 (4, './Data/binary_segment/80도/output04.npz'),
 (5, './Data/binary_segment/80도/output05.npz'),
 (6, './Data/binary_segment/80도/output06.npz'),
 (7, './Data/binary_segment/80도/output07.npz'),
 (8, './Data/binary_segment/80도/output08.npz'),
 (9, './Data/binary_segment/80도/output09.npz'),
 (10, './Data/binary_segment/80도/output10.npz'),
 (11, './Data/binary_segment/80도/output11.npz'),
 (12, './Data/binary_segment/80도/output12.npz'),
 (13, './Data/binary_segment/80도/output13.npz'),
 (14, './Data/binary_segment/80도/output14.npz'),
 (15, './Data/binary_segment/80도/output15.npz'),
 (16, './Data/binary_segment/80도/output16.npz'),
 (17, './Data/binary_segment/80도/output17.npz'),
 (18, './Data/binary_segment/80도/output18.npz'),
 (19, './Data/binary_segment/80도/output19.npz'),
 (20, './Data/binary_segment/8

In [13]:
list(enumerate(samples_vad_seg_100))

[(0, './Data/binary_segment/100도/output00.npz'),
 (1, './Data/binary_segment/100도/output01.npz'),
 (2, './Data/binary_segment/100도/output02.npz'),
 (3, './Data/binary_segment/100도/output03.npz'),
 (4, './Data/binary_segment/100도/output04.npz'),
 (5, './Data/binary_segment/100도/output05.npz'),
 (6, './Data/binary_segment/100도/output06.npz'),
 (7, './Data/binary_segment/100도/output07.npz'),
 (8, './Data/binary_segment/100도/output08.npz'),
 (9, './Data/binary_segment/100도/output09.npz'),
 (10, './Data/binary_segment/100도/output10.npz'),
 (11, './Data/binary_segment/100도/output11.npz'),
 (12, './Data/binary_segment/100도/output12.npz'),
 (13, './Data/binary_segment/100도/output13.npz'),
 (14, './Data/binary_segment/100도/output14.npz'),
 (15, './Data/binary_segment/100도/output15.npz'),
 (16, './Data/binary_segment/100도/output16.npz'),
 (17, './Data/binary_segment/100도/output17.npz'),
 (18, './Data/binary_segment/100도/output18.npz'),
 (19, './Data/binary_segment/100도/output19.npz'),
 (20, './D

In [14]:
list(enumerate(samples_vad_seg_140))

[(0, './Data/binary_segment/140도/output00.npz'),
 (1, './Data/binary_segment/140도/output01.npz'),
 (2, './Data/binary_segment/140도/output02.npz'),
 (3, './Data/binary_segment/140도/output03.npz'),
 (4, './Data/binary_segment/140도/output04.npz'),
 (5, './Data/binary_segment/140도/output05.npz'),
 (6, './Data/binary_segment/140도/output06.npz'),
 (7, './Data/binary_segment/140도/output07.npz'),
 (8, './Data/binary_segment/140도/output08.npz'),
 (9, './Data/binary_segment/140도/output09.npz'),
 (10, './Data/binary_segment/140도/output10.npz'),
 (11, './Data/binary_segment/140도/output11.npz'),
 (12, './Data/binary_segment/140도/output12.npz'),
 (13, './Data/binary_segment/140도/output13.npz'),
 (14, './Data/binary_segment/140도/output14.npz'),
 (15, './Data/binary_segment/140도/output15.npz'),
 (16, './Data/binary_segment/140도/output16.npz'),
 (17, './Data/binary_segment/140도/output17.npz'),
 (18, './Data/binary_segment/140도/output18.npz'),
 (19, './Data/binary_segment/140도/output19.npz'),
 (20, './D

In [15]:
list(enumerate(samples_vad_seg_160))

[(0, './Data/binary_segment/160도/output00.npz'),
 (1, './Data/binary_segment/160도/output01.npz'),
 (2, './Data/binary_segment/160도/output02.npz'),
 (3, './Data/binary_segment/160도/output03.npz'),
 (4, './Data/binary_segment/160도/output04.npz'),
 (5, './Data/binary_segment/160도/output05.npz'),
 (6, './Data/binary_segment/160도/output06.npz'),
 (7, './Data/binary_segment/160도/output07.npz'),
 (8, './Data/binary_segment/160도/output08.npz'),
 (9, './Data/binary_segment/160도/output09.npz'),
 (10, './Data/binary_segment/160도/output10.npz'),
 (11, './Data/binary_segment/160도/output11.npz'),
 (12, './Data/binary_segment/160도/output12.npz'),
 (13, './Data/binary_segment/160도/output13.npz'),
 (14, './Data/binary_segment/160도/output14.npz'),
 (15, './Data/binary_segment/160도/output15.npz'),
 (16, './Data/binary_segment/160도/output16.npz'),
 (17, './Data/binary_segment/160도/output17.npz'),
 (18, './Data/binary_segment/160도/output18.npz'),
 (19, './Data/binary_segment/160도/output19.npz'),
 (20, './D

In [16]:
sample_data_repo = os.path.join('.', 'Data', 'sample_data', 't3_audio')
samples = glob.glob(os.path.join(sample_data_repo, '**', '*wav'), recursive=True)
samples = sorted(samples)   # sort the samples
print(len(samples))

50


In [17]:
sample_data_20 = os.path.join('.', 'Data', 'sample_data', '20도')
samples_20 = glob.glob(os.path.join(sample_data_20, '**', '*wav'), recursive=True)
samples_20 = sorted(samples_20)   # sort the samples
print(len(samples_20))

36


In [18]:
sample_data_40 = os.path.join('.', 'Data', 'sample_data', '40도')
samples_40 = glob.glob(os.path.join(sample_data_40, '**', '*wav'), recursive=True)
samples_40 = sorted(samples_40)   # sort the samples
print(len(samples_40))

39


In [19]:
sample_data_80 = os.path.join('.', 'Data', 'sample_data', '80도')
samples_80 = glob.glob(os.path.join(sample_data_80, '**', '*wav'), recursive=True)
samples_80 = sorted(samples_80)   # sort the samples
print(len(samples_80))

47


In [20]:
sample_data_100 = os.path.join('.', 'Data', 'sample_data', '100도')
samples_100 = glob.glob(os.path.join(sample_data_100, '**', '*wav'), recursive=True)
samples_100 = sorted(samples_100)   # sort the samples
print(len(samples_100))

51


In [21]:
sample_data_140 = os.path.join('.', 'Data', 'sample_data', '140도')
samples_140 = glob.glob(os.path.join(sample_data_140, '**', '*wav'), recursive=True)
samples_140 = sorted(samples_140)   # sort the samples
print(len(samples_140))

41


In [22]:
sample_data_160 = os.path.join('.', 'Data', 'sample_data', '160도')
samples_160 = glob.glob(os.path.join(sample_data_160, '**', '*wav'), recursive=True)
samples_160 = sorted(samples_160)   # sort the samples
print(len(samples_160))

51


In [23]:
def mag_phase(file_path, sr=48000, n_fft=1024, hop_length=512, db=False, n_mels=50) :
    audio, sr = librosa.load(file_path, sr=sr, mono=False)   # 원래의 sr, stereo
    DL = librosa.stft(audio[0], n_fft=n_fft, hop_length=hop_length)
    DL_mag, DL_phase = librosa.magphase(DL)
    
    DR = librosa.stft(audio[1], n_fft=n_fft, hop_length=hop_length)
    DR_mag, DR_phase = librosa.magphase(DR)
    
    if db :
        DL_mag = librosa.core.amplitude_to_db(DL_mag)
        DR_mag = librosa.core.amplitude_to_db(DR_mag)
     
    # rescale the right magnitudes w.r.t left channel magnitude 
    avg = DL_mag.mean()     
    stdv = DL_mag.std()
    DL_mag = (DL_mag - avg)/stdv
    DR_mag = (DR_mag - avg)/stdv
    
    # return( (DL_mag, np.angle(DL_phase)), (DR_mag, np.angle(DR_phase)) )
    return( (DL_mag[1:, :], np.angle(DL_phase)[1:, :]), (DR_mag[1:, :], np.angle(DR_phase)[1:, :]) )

In [24]:
def generate_instances(array_2d, seq_len, hop, label):
    """
    array_2d : ndarray.  STFT magnitude or phase.
    dest_path : file path
    seq_len : number of frames in an instance.
    label : segmented labels.  0 and 1's. The same length as original wav file of the audio sample. 
    """
    row_size, col_size = array_2d.shape[0], array_2d.shape[1]
    ratio = len(label)/col_size  # ratio : how many data points per frame 
    stack_array = []    # 4D tensor that will hold the instances
    label_array = []

    j=0
    while j <= (col_size - (seq_len+1)): 
        context_frame = array_2d[:, j:(j+seq_len)]
        # seg_label = round( label[int(j*ratio):int((j+seq_len)*ratio)].mean() ) 
        threshold = 0.5  # if greater than the threshold, then speech 
        seg_label = 1 if label[int(j*ratio):int((j+seq_len)*ratio)].mean() > threshold else 0

#         # store the instances
#         dest_path_ext = ''.join([dest_path, '_', str(j)])
#         os.makedirs(os.path.dirname(dest_path_ext), exist_ok=True)

#         np.savez(dest_path_ext, spectrogram = context_frame,
#                  label=seg_label)
        
        stack_array.append(context_frame[:,:,np.newaxis])   # make context_frame to 3d tensor & append 
        label_array.append(seg_label)
            
        j = j+hop
        
    return np.stack(stack_array, axis=0), label_array

In [25]:
no_samples = len(samples) 

mag_L_instances = []    # elements are ndarrays
mag_R_instances = []
phase_L_instances = []
phase_R_instances = []
label_instances = []         # elements are lists

for i in range(0, no_samples):
    voice_noise_label = np.load(samples_vad_seg[i])
    if('npy' in samples_vad_seg[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

mag_L_instances[0].shape, phase_R_instances[0].shape, label_instances[0].shape
# the first sample produced 15 instances.

50 50 50


((17, 512, 100, 1), (17, 512, 100, 1), (17,))

In [26]:
for i in range(0, len(samples_20)):
    voice_noise_label = np.load(samples_vad_seg_20[i])
    if('npy' in samples_vad_seg_20[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_20[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

86 86 86


In [27]:
for i in range(0, len(samples_40)):
    voice_noise_label = np.load(samples_vad_seg_40[i])
    if('npy' in samples_vad_seg_40[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_40[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

125 125 125


In [28]:
for i in range(0, len(samples_80)):
    voice_noise_label = np.load(samples_vad_seg_80[i])
    if('npy' in samples_vad_seg_80[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_80[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

172 172 172


In [29]:
for i in range(0, len(samples_100)):
    voice_noise_label = np.load(samples_vad_seg_100[i])
    if('npy' in samples_vad_seg_100[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_100[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

223 223 223


In [30]:
for i in range(0, len(samples_140)):
    voice_noise_label = np.load(samples_vad_seg_140[i])
    if('npy' in samples_vad_seg_140[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_140[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

264 264 264


In [31]:
for i in range(0, len(samples_160)):
    voice_noise_label = np.load(samples_vad_seg_160[i])
    if('npy' in samples_vad_seg_160[i].split('/')[-1]):
        label = voice_noise_label[0]        # use the left channel label.  this take care of 0 degree problem
    else:                                   # npz file
        label = voice_noise_label["label"]    
    (mag_L, phase_L), (mag_R, phase_R) = mag_phase(samples_160[i], db=True)
    
    # generate instances with 1.16 sec duration (100 frames), at every 0.116 sec apart (10 hops)
    mag_L_instances_sub, _ = generate_instances(mag_L, 100, 10, label)
    
    mag_R_instances_sub, _ = generate_instances(mag_R, 100, 10, label)
    
    phase_L_instances_sub, _ = generate_instances(phase_L, 100, 10, label)
    
    phase_R_instances_sub, label_sub = generate_instances(phase_R, 100, 10, label)
    
    mag_L_instances.append(mag_L_instances_sub)
    mag_R_instances.append(mag_R_instances_sub)
    phase_L_instances.append(phase_L_instances_sub)
    phase_R_instances.append(phase_R_instances_sub)
    
    label_instances.append(np.array(label_sub))
    

print(len(mag_L_instances), len(phase_R_instances), len(label_instances))

315 315 315


In [32]:
n_20 = 50 + len(samples_20)
n_40 = n_20 + len(samples_40)
n_80 = n_40 + len(samples_80)
n_100 = n_80 + len(samples_100)
n_140 = n_100 + len(samples_140)
n_160 = n_140 + len(samples_160)

In [33]:
total_instances_tensor = []

for i in range(0, n_160):
    concat_tensor = np.concatenate([mag_L_instances[i], phase_L_instances[i], 
                                    mag_R_instances[i], phase_R_instances[i]], axis = -1)
    total_instances_tensor.append(concat_tensor)

In [34]:
total_instances_tensor[0].shape

(17, 512, 100, 4)

In [35]:
total_label = []

for i in range(0, n_160):
    array_label = np.array(label_instances[i])
    total_label.append(array_label)

In [36]:
vad_label = []

for i in range(0, n_160):
    array_label = np.array(label_instances[i])
    vad_label.append(array_label)

In [37]:
for i in range(0, n_160):
    print(total_instances_tensor[i].shape, total_label[i].shape)

(17, 512, 100, 4) (17,)
(6, 512, 100, 4) (6,)
(14, 512, 100, 4) (14,)
(22, 512, 100, 4) (22,)
(12, 512, 100, 4) (12,)
(13, 512, 100, 4) (13,)
(31, 512, 100, 4) (31,)
(20, 512, 100, 4) (20,)
(8, 512, 100, 4) (8,)
(17, 512, 100, 4) (17,)
(14, 512, 100, 4) (14,)
(26, 512, 100, 4) (26,)
(18, 512, 100, 4) (18,)
(22, 512, 100, 4) (22,)
(20, 512, 100, 4) (20,)
(27, 512, 100, 4) (27,)
(16, 512, 100, 4) (16,)
(13, 512, 100, 4) (13,)
(21, 512, 100, 4) (21,)
(28, 512, 100, 4) (28,)
(5, 512, 100, 4) (5,)
(15, 512, 100, 4) (15,)
(20, 512, 100, 4) (20,)
(21, 512, 100, 4) (21,)
(16, 512, 100, 4) (16,)
(9, 512, 100, 4) (9,)
(21, 512, 100, 4) (21,)
(13, 512, 100, 4) (13,)
(19, 512, 100, 4) (19,)
(23, 512, 100, 4) (23,)
(21, 512, 100, 4) (21,)
(21, 512, 100, 4) (21,)
(8, 512, 100, 4) (8,)
(28, 512, 100, 4) (28,)
(18, 512, 100, 4) (18,)
(12, 512, 100, 4) (12,)
(19, 512, 100, 4) (19,)
(15, 512, 100, 4) (15,)
(11, 512, 100, 4) (11,)
(26, 512, 100, 4) (26,)
(43, 512, 100, 4) (43,)
(28, 512, 100, 4) (28,)
(3

In [38]:
val = 0
for i in range(0, n_160):
    val = val + total_instances_tensor[i].shape[0]
    
val

30862

In [39]:
for i in range(0, 12):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -90

for i in range(12, 25):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -30
            
for i in range(25, 38):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 30
            
for i in range(38, 50):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 90
            
for i in range(50, n_20):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -70

for i in range(n_20, n_40):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -50
            
for i in range(n_40, n_80):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = -10
            
for i in range(n_80, n_100):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 10
            
for i in range(n_100, n_140):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 50
            
for i in range(n_140, n_160):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 70
              
total_label

[array([-90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90,
        -90, -90, -90, -90]),
 array([-90, -90, -90, -90, -90, -90]),
 array([  0,   0,   0,   0,   0,   0,   0, -90, -90, -90, -90, -90, -90,
        -90]),
 array([-90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90,
        -90, -90, -90, -90, -90, -90, -90, -90,   0]),
 array([-90, -90, -90, -90, -90, -90, -90, -90,   0,   0,   0,   0]),
 array([-90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90]),
 array([  0,   0,   0,   0,   0,   0,   0, -90, -90, -90, -90, -90, -90,
        -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90, -90,
        -90, -90, -90,   0,   0]),
 array([  0,   0,   0,   0,   0, -90, -90, -90, -90, -90, -90, -90, -90,
        -90, -90, -90,   0,   0,   0,   0]),
 array([-90, -90, -90, -90, -90, -90, -90, -90]),
 array([  0,   0,   0,   0,   0, -90, -90, -90, -90, -90, -90, -90, -90,
        -90,   0,   0,   0]),
 array([-90, -90, -90, -90, -90, -90, -90, -

In [40]:
np.random.seed(19)
idx = np.random.permutation(n_160)
idx

array([ 23,   8, 258, 138, 199, 145, 234, 211, 253, 101, 135, 284, 148,
        48,  12,  75, 179, 209,  61,  90, 243,   1, 229,  27,  36, 142,
        60, 103, 302, 121,  92, 210,  24,  15,  49,   2,  65,   6,  17,
        95, 165, 259,  98, 257, 190, 177,  37, 197, 255, 120,  64,  13,
       187, 227, 290, 285, 141, 281, 132, 168,  62, 251, 207, 223, 174,
       205, 216,  96, 119, 144,  20, 117, 171, 252, 249, 175,  86, 154,
       156, 296, 304, 184, 137, 200, 222, 300, 192, 272,  16, 176, 149,
       208, 129, 306,  87, 289, 250,  78, 143,  74, 113, 279, 276,  54,
       189, 136,  40, 139, 283, 128, 270, 160, 241, 288, 150, 185, 278,
       214, 181,  33,  66,  10, 217, 297, 230, 235, 158, 202,  11,  45,
        41,  26,  31, 312,  34, 146,  91, 277,  57, 237, 108,  71, 161,
       178, 115,  30,  35,  72, 254, 307,  50, 163, 293,  82,   7, 294,
        42,  58, 180,  14, 314, 130, 219, 238, 186,  59, 299, 280,  70,
        81, 261,  83, 164, 242, 155,  89, 204, 292, 236, 104, 15

In [41]:
X = []
y = []
vad = []

for i in range(0, n_160):
    X.append(total_instances_tensor[idx[i]])
    y.append(total_label[idx[i]])
    vad.append(vad_label[idx[i]])

In [42]:
for i in range(0, n_160):
    print(X[i].shape[0], y[i].shape, vad[i].shape)

21 (21,) (21,)
8 (8,) (8,)
179 (179,) (179,)
179 (179,) (179,)
179 (179,) (179,)
28 (28,) (28,)
179 (179,) (179,)
28 (28,) (28,)
743 (743,) (743,)
28 (28,) (28,)
179 (179,) (179,)
28 (28,) (28,)
179 (179,) (179,)
18 (18,) (18,)
18 (18,) (18,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
179 (179,) (179,)
28 (28,) (28,)
6 (6,) (6,)
28 (28,) (28,)
13 (13,) (13,)
19 (19,) (19,)
179 (179,) (179,)
179 (179,) (179,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
179 (179,) (179,)
179 (179,) (179,)
16 (16,) (16,)
27 (27,) (27,)
16 (16,) (16,)
14 (14,) (14,)
179 (179,) (179,)
31 (31,) (31,)
13 (13,) (13,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
743 (743,) (743,)
15 (15,) (15,)
179 (179,) (179,)
28 (28,) (28,)
28 (28,) (28,)
179 (179,) (179,)
22 (22,) (22,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
28 (28,) (28,)
179 (179,) (179,)
179 (179,) (179,)
28 (28,) (28,)
179 (179,) (179,)
28 (28,) (28,)
179 (179,) (179,)
179 (179,) (179,

In [43]:
train_idx = n_160
X_train = np.concatenate(X[:train_idx], axis=0)
y_train = np.concatenate(y[:train_idx], axis=0)
vad_train = np.concatenate(vad[:train_idx], axis=0)

X_train.shape, y_train.shape, vad_train.shape

((30862, 512, 100, 4), (30862,), (30862,))

# Regression

In [44]:
from keras.layers import Conv2D, MaxPooling2D, Input, Flatten, Dropout, Dense, Reshape, Conv1D
from keras.models import Model

input_spectrogram = Input(shape=(X_train.shape[1], X_train.shape[2], X_train.shape[3]))

conv_1 = Conv2D(16, (3, 3), activation='relu')(input_spectrogram)
max_pool_1 = MaxPooling2D((2, 2))(conv_1)

conv_2 = Conv2D(32, (3, 3), activation='relu')(max_pool_1)
max_pool_2 = MaxPooling2D((2, 2))(conv_2)

conv_3 = Conv2D(64, (3, 3), strides=(2,1), activation='relu')(max_pool_2)
conv_3_1 = Conv2D(64, (3, 2), strides=(2,1), activation='relu')(conv_3)
max_pool_3 = MaxPooling2D((3, 2), name='max_pool_3')(conv_3_1)

shape_max_pool_3 = max_pool_3.get_shape().as_list()    # (None, height, width, channel)
print("shape_max_pool_3 : ", shape_max_pool_3)
# reshaped = layers.Reshape((-1, shape_list[1]*shape_list[3]))(max_pool_3)

conv_4 = Conv2D(1024, (shape_max_pool_3[1], 1), padding='valid', activation='relu')(max_pool_3)
shape_conv_4 = conv_4.get_shape().as_list()
print("shape_conv_4 : ", shape_conv_4)

reshaped = Reshape((shape_conv_4[2], shape_conv_4[3]))(conv_4) # reshape to (timesteps, features) explicitly 

conv_5 = Conv1D(512, kernel_size=3, activation='relu')(reshaped)

flatten = Flatten()(conv_5)
# flatten_drop = Dropout(0.3)(flatten)

fc1 = Dense(32, activation='relu')(flatten)
fc1_drop = Dropout(0.1)(fc1)

vad_out = Dense(1, activation='sigmoid', name='vad_output')(fc1_drop)
dense_out = Dense(1, activation='linear', name='reg_output')(fc1_drop)


model_reg = Model(inputs=input_spectrogram, outputs=[vad_out, dense_out])
model_reg.summary()

shape_max_pool_3 :  [None, 10, 10, 64]
shape_conv_4 :  [None, 1, 10, 1024]
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 512, 100, 4)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 510, 98, 16)  592         input_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 255, 49, 16)  0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 253, 47, 32)  4640        max_pooling2d_1[0][0]            
__________________________________

Using TensorFlow backend.


In [45]:
from keras.utils import multi_gpu_model

model_reg = multi_gpu_model(model_reg, gpus=8, cpu_relocation=True)

In [46]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

model_reg.compile(optimizer ='rmsprop', loss={'vad_output' : 'binary_crossentropy', 'reg_output' : 'mse'},
              metrics ={'vad_output' : 'acc', 'reg_output' : 'mse'})

callbacks_list = [EarlyStopping(monitor='loss', patience=20),
                 ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10)]

history = model_reg.fit(X_train, [vad_train, y_train],
                    epochs=150, batch_size=64, 
                    callbacks=callbacks_list,
                    shuffle=True)

Epoch 1/150
30862/30862 [==============================] - 74s 2ms/step - loss: 370.5657 - vad_output_loss: 0.4964 - reg_output_loss: 370.0692 - vad_output_acc: 0.8650 - reg_output_mean_squared_error: 370.0692
Epoch 2/150
30862/30862 [==============================] - 73s 2ms/step - loss: 147.8936 - vad_output_loss: 0.1218 - reg_output_loss: 147.7718 - vad_output_acc: 0.9711 - reg_output_mean_squared_error: 147.7718
Epoch 3/150
30862/30862 [==============================] - 66s 2ms/step - loss: 82.1161 - vad_output_loss: 0.1009 - reg_output_loss: 82.0152 - vad_output_acc: 0.9779 - reg_output_mean_squared_error: 82.0152
Epoch 4/150
30862/30862 [==============================] - 66s 2ms/step - loss: 55.8691 - vad_output_loss: 0.0907 - reg_output_loss: 55.7784 - vad_output_acc: 0.9802 - reg_output_mean_squared_error: 55.7784
Epoch 5/150
30862/30862 [==============================] - 65s 2ms/step - loss: 44.8642 - vad_output_loss: 0.0737 - reg_output_loss: 44.7905 - vad_output_acc: 0.9875 

30862/30862 [==============================] - 68s 2ms/step - loss: 10.6625 - vad_output_loss: 0.0112 - reg_output_loss: 10.6513 - vad_output_acc: 0.9985 - reg_output_mean_squared_error: 10.6513
Epoch 41/150
30862/30862 [==============================] - 68s 2ms/step - loss: 10.2934 - vad_output_loss: 0.0132 - reg_output_loss: 10.2802 - vad_output_acc: 0.9983 - reg_output_mean_squared_error: 10.2802
Epoch 42/150
30862/30862 [==============================] - 68s 2ms/step - loss: 9.9310 - vad_output_loss: 0.0092 - reg_output_loss: 9.9218 - vad_output_acc: 0.9986 - reg_output_mean_squared_error: 9.9218
Epoch 43/150
30862/30862 [==============================] - 68s 2ms/step - loss: 10.3271 - vad_output_loss: 0.0092 - reg_output_loss: 10.3179 - vad_output_acc: 0.9985 - reg_output_mean_squared_error: 10.3179
Epoch 44/150
30862/30862 [==============================] - 68s 2ms/step - loss: 10.1761 - vad_output_loss: 0.0113 - reg_output_loss: 10.1648 - vad_output_acc: 0.9984 - reg_output_mean

30862/30862 [==============================] - 68s 2ms/step - loss: 9.0716 - vad_output_loss: 0.0086 - reg_output_loss: 9.0630 - vad_output_acc: 0.9988 - reg_output_mean_squared_error: 9.0630
Epoch 80/150
30862/30862 [==============================] - 68s 2ms/step - loss: 9.1938 - vad_output_loss: 0.0078 - reg_output_loss: 9.1861 - vad_output_acc: 0.9989 - reg_output_mean_squared_error: 9.1861
Epoch 81/150
30862/30862 [==============================] - 68s 2ms/step - loss: 9.0163 - vad_output_loss: 0.0048 - reg_output_loss: 9.0116 - vad_output_acc: 0.9993 - reg_output_mean_squared_error: 9.0116
Epoch 82/150
30862/30862 [==============================] - 68s 2ms/step - loss: 8.8518 - vad_output_loss: 0.0061 - reg_output_loss: 8.8457 - vad_output_acc: 0.9992 - reg_output_mean_squared_error: 8.8457
Epoch 83/150
30862/30862 [==============================] - 68s 2ms/step - loss: 8.6670 - vad_output_loss: 0.0057 - reg_output_loss: 8.6613 - vad_output_acc: 0.9991 - reg_output_mean_squared_er

30862/30862 [==============================] - 68s 2ms/step - loss: 4.7191 - vad_output_loss: 0.0017 - reg_output_loss: 4.7174 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.7174
Epoch 119/150
30862/30862 [==============================] - 68s 2ms/step - loss: 4.5152 - vad_output_loss: 0.0020 - reg_output_loss: 4.5132 - vad_output_acc: 0.9998 - reg_output_mean_squared_error: 4.5132
Epoch 120/150
30862/30862 [==============================] - 68s 2ms/step - loss: 4.6149 - vad_output_loss: 0.0016 - reg_output_loss: 4.6133 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.6133
Epoch 121/150
30862/30862 [==============================] - 68s 2ms/step - loss: 4.4445 - vad_output_loss: 0.0017 - reg_output_loss: 4.4428 - vad_output_acc: 0.9999 - reg_output_mean_squared_error: 4.4428
Epoch 122/150
30862/30862 [==============================] - 68s 2ms/step - loss: 4.6832 - vad_output_loss: 0.0016 - reg_output_loss: 4.6816 - vad_output_acc: 0.9999 - reg_output_mean_square

In [47]:
model_reg.save('STFT_2DCNN_1DCNN_regression_multi.h5')

# Classification

In [48]:
total_label = []

for i in range(0, n_160):
    array_label = np.array(label_instances[i])
    total_label.append(array_label)

In [49]:
vad_label = []

for i in range(0, n_160):
    array_label = np.array(label_instances[i])
    vad_label.append(array_label)

In [50]:
for i in range(0, 12):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 1

for i in range(12, 25):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 4
            
for i in range(25, 38):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 7
            
for i in range(38, 50):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 10
            
for i in range(50, n_20):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 2

for i in range(n_20, n_40):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 3
            
for i in range(n_40, n_80):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 5
            
for i in range(n_80, n_100):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 6
            
for i in range(n_100, n_140):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 8
            
for i in range(n_140, n_160):
    for j in range(0, len(total_label[i])):
        if(total_label[i][j] == 1):
            total_label[i][j] = 9
              
total_label

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0]),
 array([0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4

In [51]:
np.random.seed(19)
idx = np.random.permutation(n_160)
idx

array([ 23,   8, 258, 138, 199, 145, 234, 211, 253, 101, 135, 284, 148,
        48,  12,  75, 179, 209,  61,  90, 243,   1, 229,  27,  36, 142,
        60, 103, 302, 121,  92, 210,  24,  15,  49,   2,  65,   6,  17,
        95, 165, 259,  98, 257, 190, 177,  37, 197, 255, 120,  64,  13,
       187, 227, 290, 285, 141, 281, 132, 168,  62, 251, 207, 223, 174,
       205, 216,  96, 119, 144,  20, 117, 171, 252, 249, 175,  86, 154,
       156, 296, 304, 184, 137, 200, 222, 300, 192, 272,  16, 176, 149,
       208, 129, 306,  87, 289, 250,  78, 143,  74, 113, 279, 276,  54,
       189, 136,  40, 139, 283, 128, 270, 160, 241, 288, 150, 185, 278,
       214, 181,  33,  66,  10, 217, 297, 230, 235, 158, 202,  11,  45,
        41,  26,  31, 312,  34, 146,  91, 277,  57, 237, 108,  71, 161,
       178, 115,  30,  35,  72, 254, 307,  50, 163, 293,  82,   7, 294,
        42,  58, 180,  14, 314, 130, 219, 238, 186,  59, 299, 280,  70,
        81, 261,  83, 164, 242, 155,  89, 204, 292, 236, 104, 15

In [52]:
X = []
y = []
vad = []

for i in range(0, n_160):
    X.append(total_instances_tensor[idx[i]])
    y.append(total_label[idx[i]])
    vad.append(vad_label[idx[i]])

In [53]:
train_idx = n_160
X_train = np.concatenate(X[:train_idx], axis=0)
y_train = np.concatenate(y[:train_idx], axis=0)
vad_train = np.concatenate(vad[:train_idx], axis=0)

X_train.shape, y_train.shape, vad_train.shape

((30862, 512, 100, 4), (30862,), (30862,))

In [54]:
from keras.utils import np_utils

y_train = np_utils.to_categorical(y_train, 11)

In [55]:
from keras.layers import Conv2D, MaxPooling2D, Input, Flatten, Dropout, Dense, Reshape, Conv1D
from keras.models import Model

input_spectrogram = Input(shape=(X_train.shape[1], X_train.shape[2], X_train.shape[3]))

conv_1 = Conv2D(16, (3, 3), activation='relu')(input_spectrogram)
max_pool_1 = MaxPooling2D((2, 2))(conv_1)

conv_2 = Conv2D(32, (3, 3), activation='relu')(max_pool_1)
max_pool_2 = MaxPooling2D((2, 2))(conv_2)

conv_3 = Conv2D(64, (3, 3), strides=(2,1), activation='relu')(max_pool_2)
conv_3_1 = Conv2D(64, (3, 2), strides=(2,1), activation='relu')(conv_3)
max_pool_3 = MaxPooling2D((3, 2), name='max_pool_3')(conv_3_1)

shape_max_pool_3 = max_pool_3.get_shape().as_list()    # (None, height, width, channel)
print("shape_max_pool_3 : ", shape_max_pool_3)
# reshaped = layers.Reshape((-1, shape_list[1]*shape_list[3]))(max_pool_3)

conv_4 = Conv2D(1024, (shape_max_pool_3[1], 1), padding='valid', activation='relu')(max_pool_3)
shape_conv_4 = conv_4.get_shape().as_list()
print("shape_conv_4 : ", shape_conv_4)

reshaped = Reshape((shape_conv_4[2], shape_conv_4[3]))(conv_4) # reshape to (timesteps, features) explicitly 

conv_5 = Conv1D(512, kernel_size=3, activation='relu')(reshaped)

flatten = Flatten()(conv_5)
# flatten_drop = Dropout(0.3)(flatten)

fc1 = Dense(32, activation='relu')(flatten)
fc1_drop = Dropout(0.1)(fc1)

vad_out = Dense(1, activation='sigmoid', name='vad_output')(fc1_drop)
dense_out = Dense(11, activation='softmax', name='clf_output')(fc1_drop)

model_clf = Model(inputs=input_spectrogram, outputs=[vad_out, dense_out])
model_clf.summary()

shape_max_pool_3 :  [None, 10, 10, 64]
shape_conv_4 :  [None, 1, 10, 1024]
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 512, 100, 4)  0                                            
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 510, 98, 16)  592         input_2[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)  (None, 255, 49, 16)  0           conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 253, 47, 32)  4640        max_pooling2d_3[0][0]            
__________________________________

In [56]:
from keras.utils import multi_gpu_model

model_clf = multi_gpu_model(model_clf, gpus=8, cpu_relocation=True)

In [57]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

model_clf.compile(optimizer ='rmsprop', loss={'vad_output' : 'binary_crossentropy', 'clf_output' : 'categorical_crossentropy'},
              metrics ={'vad_output' : 'acc', 'clf_output' : 'acc'})

model_path = 'STFT_2DCNN_1DCNN_clf_multi.h5'
callbacks_list = [EarlyStopping(monitor='loss', patience=20),
                 ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10),
                 ModelCheckpoint(filepath=model_path, monitor='loss', verbose=1, save_best_only=True)]

history = model_clf.fit(X_train, [vad_train, y_train],
                    epochs=150, batch_size=64, 
                    callbacks=callbacks_list,
                    shuffle=True)

Epoch 1/150
30862/30862 [==============================] - 68s 2ms/step - loss: 0.6015 - vad_output_loss: 0.1076 - clf_output_loss: 0.4939 - vad_output_acc: 0.9574 - clf_output_acc: 0.8430

Epoch 00001: loss improved from inf to 0.60154, saving model to STFT_2DCNN_1DCNN_clf_multi.h5
Epoch 2/150
30862/30862 [==============================] - 71s 2ms/step - loss: 0.2604 - vad_output_loss: 0.0300 - clf_output_loss: 0.2305 - vad_output_acc: 0.9892 - clf_output_acc: 0.9087

Epoch 00002: loss improved from 0.60154 to 0.26043, saving model to STFT_2DCNN_1DCNN_clf_multi.h5
Epoch 3/150
30862/30862 [==============================] - 70s 2ms/step - loss: 0.1845 - vad_output_loss: 0.0251 - clf_output_loss: 0.1594 - vad_output_acc: 0.9902 - clf_output_acc: 0.9379

Epoch 00003: loss improved from 0.26043 to 0.18454, saving model to STFT_2DCNN_1DCNN_clf_multi.h5
Epoch 4/150
30862/30862 [==============================] - 67s 2ms/step - loss: 0.1362 - vad_output_loss: 0.0210 - clf_output_loss: 0.1152 -

30862/30862 [==============================] - 68s 2ms/step - loss: 0.0019 - vad_output_loss: 6.9282e-04 - clf_output_loss: 0.0012 - vad_output_acc: 0.9999 - clf_output_acc: 0.9998

Epoch 00031: loss did not improve from 0.00183
Epoch 32/150
30862/30862 [==============================] - 69s 2ms/step - loss: 0.0015 - vad_output_loss: 5.3275e-04 - clf_output_loss: 9.6673e-04 - vad_output_acc: 1.0000 - clf_output_acc: 0.9999

Epoch 00032: loss improved from 0.00183 to 0.00150, saving model to STFT_2DCNN_1DCNN_clf_multi.h5
Epoch 33/150
30862/30862 [==============================] - 68s 2ms/step - loss: 0.0014 - vad_output_loss: 5.2819e-04 - clf_output_loss: 9.1162e-04 - vad_output_acc: 1.0000 - clf_output_acc: 0.9999

Epoch 00033: loss improved from 0.00150 to 0.00144, saving model to STFT_2DCNN_1DCNN_clf_multi.h5
Epoch 34/150
30862/30862 [==============================] - 68s 2ms/step - loss: 0.0023 - vad_output_loss: 5.7240e-04 - clf_output_loss: 0.0017 - vad_output_acc: 0.9999 - clf_ou

30862/30862 [==============================] - 69s 2ms/step - loss: 5.2300e-04 - vad_output_loss: 5.6973e-07 - clf_output_loss: 5.2244e-04 - vad_output_acc: 1.0000 - clf_output_acc: 1.0000

Epoch 00063: loss did not improve from 0.00000
Epoch 64/150
30862/30862 [==============================] - 69s 2ms/step - loss: 4.0738e-05 - vad_output_loss: 1.0349e-07 - clf_output_loss: 4.0634e-05 - vad_output_acc: 1.0000 - clf_output_acc: 1.0000

Epoch 00064: loss did not improve from 0.00000
Epoch 65/150
30862/30862 [==============================] - 69s 2ms/step - loss: 1.4952e-05 - vad_output_loss: 1.0437e-07 - clf_output_loss: 1.4848e-05 - vad_output_acc: 1.0000 - clf_output_acc: 1.0000

Epoch 00065: loss did not improve from 0.00000
Epoch 66/150
30862/30862 [==============================] - 69s 2ms/step - loss: 5.9771e-05 - vad_output_loss: 6.3295e-07 - clf_output_loss: 5.9138e-05 - vad_output_acc: 1.0000 - clf_output_acc: 1.0000

Epoch 00066: loss did not improve from 0.00000
Epoch 67/150


In [50]:
# model_clf.save('STFT_2DCNN_1DCNN_clf_multi.h5')